# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github Blog Template
url: http://nameyule.github.io
feed: /atom.xml
author_info: <a href="http://nameyule.github.io/">老于乐</a>

myblog:
  gavatar: images/2.jpg
  gpname: 老于乐
  linkedin: http://www.linkedin.com/in/erichurrah/
  github: https://github.com/nameyule
  email: mailto:yule.hurrah@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]

theme: jekyll-theme-cayman